"""
rebuild_q2_from_ssd_pdf.py — STAGING ONLY (revised: LSC = loyalty_sales / $25).

Source of truth: SSD 6.15.26.pdf parsed by the deployed app and preserved in
db.upload_jobs (job_id 8f358c51-f752-4d8b-9dad-8ece16559117).

OPERATOR CORRECTION: LSC IS sourced from loyalty_sales in this PDF. The
existing live snapshot's lsc_count column was generated by an undocumented
$/LSC conversion. Empirically verified $25/LSC against >10 servers (e.g.
Lakeisha $1100 -> 44 LSC, Kitti $1150 -> 46, Treyanna $200 -> 8, Kahiaulani
$125 -> 5, Jamie $150 -> 6, Adriana $125 -> 5, Jose $275 -> 11, Caitlin
$25 -> 1).  Conversion applied: lsc_count = round(loyalty_sales / 25).

Manual extraction corrections from the PDF text (vs the deployed app's
parse_result):
   - Ethan Dever loyalty_sales: $325,000.63  ->  $325.00  (OCR artifact;
     PDF prints $325.00).

No writes to `snapshot_workflow` (live). Updates only
`snapshot_workflow_staging.Q2_REBUILD_STAGED` AND
/app/backend/q2_pos_truth_v2.csv.
"""

import asyncio
import csv
import os
import sys
from typing import Any, Dict, List, Optional, Tuple

from dotenv import load_dotenv
from motor.motor_asyncio import AsyncIOMotorClient

load_dotenv("/app/backend/.env")
sys.path.insert(0, "/app/backend")

from scripts.stage_q2_rebuild import Q2_ALIAS_OVERRIDE  # type: ignore

SSD_JOB_ID = "8f358c51-f752-4d8b-9dad-8ece16559117"

# Conversion: each LSC sign-up = $25 of loyalty_sales (validated against
# >10 servers' existing lsc_count in the live snapshot).
DOLLARS_PER_LSC = 25.0

# Manual OCR corrections applied on top of the deployed app's parse_result.
LOYALTY_OCR_CORRECTIONS: Dict[str, Tuple[float, float, str]] = {
    # canonical_legal -> (corrected_value, parsed_value, reason)
    "Ethan Dever": (325.00, 325000.63, "OCR concatenated cents into thousands"),
}

# Operator-supplied anchors. Must match the PDF exactly.
ANCHORS: Dict[str, Tuple[float, int, float]] = {
    "Kahiaulani Ramos": (30516.08,  643, 47.46),
    "Thomas Kozan":     (56485.89, 1168, 48.36),
    "Glennice Nguyen":  (67753.38, 1412, 47.98),
}

# Operator's regression set — must all be present with full POS data.
EXPECTED_PHANTOM_LEGALS: List[str] = [
    "Robert Mckinnon", "Tarek Araman", "Diane Peterson", "Kelsey Corkum",
    "Julian Taveras", "Eddie Garcia", "Polly Blocker", "Dylan Franklin",
    "Lexi Crandall",
]


def _norm(s: Optional[str]) -> str:
    return (s or "").strip().lower()


def _build_reverse_alias() -> Dict[str, str]:
    rev: Dict[str, str] = {}
    for canonical, aliases in Q2_ALIAS_OVERRIDE.items():
        rev[canonical.strip().lower()] = canonical
        for a in aliases:
            rev[a.strip().lower()] = canonical
    return rev


async def main() -> None:
    db = AsyncIOMotorClient(os.environ["MONGO_URL"])[os.environ["DB_NAME"]]

    # ----------------------------------------------------------------
    # 1. EXTRACT 29 parsed rows from the deployed app's preserved result.
    # ----------------------------------------------------------------
    job = await db.upload_jobs.find_one({"job_id": SSD_JOB_ID})
    if not job or job.get("status") != "completed":
        print("FATAL: parse job missing or not completed."); sys.exit(1)
    parsed = (job.get("result") or {}).get("employees") or []
    print(f"SOURCE: {job.get('filename')!r}  parsed_rows={len(parsed)}")
    print()

    reverse = _build_reverse_alias()
    pdf_rows: List[Dict[str, Any]] = []
    for r in parsed:
        pdf_name = (r.get("name") or "").strip()
        canonical = reverse.get(_norm(pdf_name), pdf_name)
        nr = dict(r)
        nr["pdf_name"] = pdf_name
        nr["canonical_legal"] = canonical
        # Apply manual OCR correction to loyalty_sales.
        if canonical in LOYALTY_OCR_CORRECTIONS:
            corrected, _, _ = LOYALTY_OCR_CORRECTIONS[canonical]
            nr["loyalty_sales_parsed"] = nr.get("loyalty_sales")
            nr["loyalty_sales"] = corrected
            nr["_loyalty_corrected"] = True
        pdf_rows.append(nr)

    # ----------------------------------------------------------------
    # 2. PRINT FULL LOYALTY COLUMN for eyeball validation.
    # ----------------------------------------------------------------
    print("=" * 96)
    print(f"LOYALTY COLUMN — all {len(pdf_rows)} servers (post OCR correction)")
    print("=" * 96)
    print(f"{'canonical legal':28}  {'loyalty $':>10}  {'parsed $':>12}  {'corrected?':>10}  {'lsc_count':>9}  {'guests_per_lsc':>15}")
    print("-" * 96)
    for r in sorted(pdf_rows, key=lambda x: -(x.get("loyalty_sales") or 0)):
        legal = r["canonical_legal"]
        loy = float(r.get("loyalty_sales") or 0)
        parsed_loy = float(r.get("loyalty_sales_parsed") or loy)
        corrected = "YES" if r.get("_loyalty_corrected") else ""
        g = int(r.get("guest_count") or 0)
        lsc_cnt = round(loy / DOLLARS_PER_LSC) if loy > 0 else 0
        gpl = round(g / lsc_cnt, 2) if lsc_cnt > 0 else 0
        print(f"  {legal:28}  ${loy:>9.2f}  ${parsed_loy:>11.2f}  {corrected:>10}  "
              f"{lsc_cnt:>9}  {gpl:>15.2f}")
    print("-" * 96)
    print()

    # ----------------------------------------------------------------
    # 3. OCR CORRECTIONS REPORT.
    # ----------------------------------------------------------------
    print("OCR CORRECTIONS APPLIED:")
    if not LOYALTY_OCR_CORRECTIONS:
        print("   (none)")
    for legal, (corr, parsed_val, why) in LOYALTY_OCR_CORRECTIONS.items():
        print(f"   ★ {legal}: parsed=${parsed_val:,.2f}  ->  corrected=${corr:,.2f}  ({why})")
    print()

    # ----------------------------------------------------------------
    # 4. OUTLIER FLAGS on loyalty distribution.
    # ----------------------------------------------------------------
    loy_vals = [float(r.get("loyalty_sales") or 0) for r in pdf_rows]
    loy_sorted = sorted(loy_vals)
    n = len(loy_sorted)
    median = loy_sorted[n // 2]
    p90 = loy_sorted[int(n * 0.9)]
    print(f"LOYALTY DISTRIBUTION  median=${median:.2f}  p90=${p90:.2f}  "
          f"min=${loy_sorted[0]:.2f}  max=${loy_sorted[-1]:.2f}")

    outlier_flags: List[Tuple[str, float, str]] = []
    for r in pdf_rows:
        legal = r["canonical_legal"]
        loy = float(r.get("loyalty_sales") or 0)
        # Operator's expected envelope: $25 - $1125. Anything outside is suspect.
        # We also keep the existing post-correction Lakeisha($1100) and Kitti($1150).
        if loy > 1500:
            outlier_flags.append((legal, loy, "ABOVE expected envelope ($25-$1125)"))
        elif loy < 0:
            outlier_flags.append((legal, loy, "NEGATIVE loyalty"))
    print(f"OUTLIER FLAGS (loyalty > $1,500): {len(outlier_flags)}")
    for legal, loy, why in outlier_flags:
        print(f"   ⚠ {legal}: ${loy:,.2f} — {why}")
    if not outlier_flags:
        print("   (none — all 29 loyalty values within the expected envelope)")
    print()

    # ----------------------------------------------------------------
    # 5. PER-ROW INTEGRITY CHECK (with corrected loyalty):
    #    Food + Liquor + Beer + Wine + Loyalty + Bar Glassware == Net.
    # ----------------------------------------------------------------
    print("=" * 96)
    print("PER-ROW INTEGRITY: Food + Liquor + Beer + Wine + Loyalty + Glass == Net")
    print("=" * 96)
    print(f"{'canonical legal':28}  {'sum':>10}  {'net':>10}  {'diff':>9}  result")
    print("-" * 96)
    integrity_fail: List[str] = []
    other_issues: List[str] = []
    for r in sorted(pdf_rows, key=lambda x: x["canonical_legal"]):
        legal = r["canonical_legal"]
        net = float(r.get("net_sales") or 0)
        g = int(r.get("guest_count") or 0)
        ppa_print = float(r.get("ppa") or 0)
        food = float(r.get("food_sales") or 0)
        liq = float(r.get("liquor_sales") or 0)
        beer = float(r.get("beer_sales") or 0)
        wine = float(r.get("wine_sales") or 0)
        loy = float(r.get("loyalty_sales") or 0)
        glass = float(r.get("bar_glassware_sales") or 0)
        cat_sum = round(food + liq + beer + wine + loy + glass, 2)
        diff = round(cat_sum - net, 2)
        ok = abs(diff) <= 0.05
        mark = "✓" if ok else "❌ FAIL"
        print(f"  {legal:28}  ${cat_sum:>9.2f}  ${net:>9.2f}  ${diff:>+8.2f}  {mark}")
        if not ok:
            integrity_fail.append(f"{legal}: sum={cat_sum} net={net} diff={diff}")
        # Side-checks
        if g <= 0:
            other_issues.append(f"{legal}: guests={g} (must be > 0)")
        if g > 0:
            ppa_calc = round(net / g, 2)
            if abs(ppa_calc - ppa_print) > 0.05:
                other_issues.append(f"{legal}: printed PPA={ppa_print} != net/guests={ppa_calc}")
        lbw_calc = round(liq + beer + wine, 2)
        lbw_print = float(r.get("lbw_total") or 0)
        if abs(lbw_calc - lbw_print) > 0.05:
            other_issues.append(f"{legal}: printed LBW={lbw_print} != L+B+W={lbw_calc}")
    print("-" * 96)
    print(f"Net-sum integrity failures: {len(integrity_fail)}")
    for s in integrity_fail:
        print(f"   ❌ {s}")
    print(f"Other side-check issues: {len(other_issues)}")
    for s in other_issues:
        print(f"   ⚠ {s}")
    if integrity_fail:
        print()
        print("HALT — per-row integrity check failed for at least one server.")
        sys.exit(2)
    print()

    # ----------------------------------------------------------------
    # 6. ANCHOR CROSS-CHECK
    # ----------------------------------------------------------------
    print("ANCHOR CROSS-CHECK:")
    by_canonical = {r["canonical_legal"]: r for r in pdf_rows}
    anchor_fail = False
    for legal, (e_net, e_g, e_ppa) in ANCHORS.items():
        r = by_canonical.get(legal)
        if not r:
            print(f"   ❌ {legal}: NOT FOUND"); anchor_fail = True; continue
        net = float(r.get("net_sales") or 0)
        g = int(r.get("guest_count") or 0)
        ppa = float(r.get("ppa") or 0)
        ok = abs(net - e_net) < 0.01 and g == e_g and abs(ppa - e_ppa) < 0.05
        mark = "✓" if ok else "❌"
        print(f"   {mark} {legal:22}  net={net:.2f}/{e_net}  guests={g}/{e_g}  ppa={ppa}/{e_ppa}")
        if not ok:
            anchor_fail = True
    if anchor_fail:
        print(); print("HALT — anchor cross-check failed."); sys.exit(3)
    print()

    # ----------------------------------------------------------------
    # 7. 9-PHANTOM REGRESSION
    # ----------------------------------------------------------------
    print("9-PHANTOM REGRESSION — all must have full POS data:")
    phantom_fail = False
    for legal in EXPECTED_PHANTOM_LEGALS:
        r = by_canonical.get(legal)
        if not r:
            print(f"   ❌ {legal}: MISSING"); phantom_fail = True; continue
        net = float(r.get("net_sales") or 0)
        g = int(r.get("guest_count") or 0)
        loy = float(r.get("loyalty_sales") or 0)
        full = net > 0 and g > 0
        mark = "✓" if full else "❌"
        print(f"   {mark} {legal:22}  net=${net:>9.2f}  guests={g:>5}  loyalty=${loy:>7.2f}  -> lsc_count={round(loy/DOLLARS_PER_LSC)}")
        if not full:
            phantom_fail = True
    if phantom_fail:
        print(); print("HALT — phantom regression failed."); sys.exit(4)
    print()

    # No-POS strict rule.
    no_pos = [r["canonical_legal"] for r in pdf_rows
              if not (float(r.get("net_sales") or 0) > 0 and int(r.get("guest_count") or 0) > 0)]
    if no_pos:
        print(f"HALT — {len(no_pos)} servers without POS: {no_pos}"); sys.exit(5)
    print("✓ Zero servers without POS data.")
    print()

    # ----------------------------------------------------------------
    # 8. ETHAN-DEVER BEFORE/AFTER (LSC + total) — to make the correction's
    #    impact visible.
    # ----------------------------------------------------------------
    from scoring_engine import QuarterSettings  # type: ignore
    qs = await db.quarter_settings.find_one({"year": 2026, "quarter": "Q2"})
    settings = QuarterSettings(**{k: v for k, v in qs.items() if k != "_id"})

    ethan = by_canonical["Ethan Dever"]
    ethan_g = int(ethan.get("guest_count") or 0)
    # BEFORE (uncorrected $325,000.63 -> lsc_count would be 13000)
    before_loy = 325000.63
    before_lsc = round(before_loy / DOLLARS_PER_LSC)
    before_gpl = round(ethan_g / before_lsc, 4) if before_lsc > 0 else 0
    before_score_lsc = round((settings.benchmark_lsc / before_gpl) * 100, 2) if before_gpl > 0 else 0
    # capped at 250
    before_score_lsc_capped = min(before_score_lsc, 250.0)
    # AFTER (corrected $325 -> lsc_count = 13)
    after_loy = float(ethan.get("loyalty_sales") or 0)
    after_lsc = round(after_loy / DOLLARS_PER_LSC)
    after_gpl = round(ethan_g / after_lsc, 4) if after_lsc > 0 else 0
    after_score_lsc = round((settings.benchmark_lsc / after_gpl) * 100, 2) if after_gpl > 0 else 0
    after_score_lsc_capped = min(after_score_lsc, 250.0)

    print("ETHAN DEVER — LSC IMPACT OF LOYALTY OCR CORRECTION:")
    print(f"   BEFORE (parsed $325,000.63): lsc_count={before_lsc}, "
          f"guests_per_lsc={before_gpl}, score_lsc={before_score_lsc} "
          f"(capped {before_score_lsc_capped})")
    print(f"   AFTER  (corrected $325.00):  lsc_count={after_lsc}, "
          f"guests_per_lsc={after_gpl}, score_lsc={after_score_lsc} "
          f"(capped {after_score_lsc_capped})")
    print(f"   Δ score_lsc (capped) = {after_score_lsc_capped - before_score_lsc_capped:+.2f}")
    print()

    # ----------------------------------------------------------------
    # 9. RESTAGE — write 29 employees with PDF POS + loyalty-derived LSC,
    #    preserved NPS/RT from prior staged doc.
    # ----------------------------------------------------------------
    staged_doc = await db.snapshot_workflow_staging.find_one({"name": "Q2_REBUILD_STAGED"})
    if not staged_doc:
        print("FATAL: staged doc missing"); sys.exit(6)
    prior_by_legal: Dict[str, Dict[str, Any]] = {}
    for e in staged_doc.get("employees") or []:
        legal = (e.get("name") or "").strip()
        if legal:
            prior_by_legal[legal] = e

    new_employees: List[Dict[str, Any]] = []
    new_rows: List[Dict[str, Any]] = []
    for r in pdf_rows:
        legal = r["canonical_legal"]
        net = float(r.get("net_sales") or 0)
        g = int(r.get("guest_count") or 0)
        ppa = float(r.get("ppa") or 0)
        liq = float(r.get("liquor_sales") or 0)
        beer = float(r.get("beer_sales") or 0)
        wine = float(r.get("wine_sales") or 0)
        food = float(r.get("food_sales") or 0)
        glass = float(r.get("bar_glassware_sales") or 0)
        loy = float(r.get("loyalty_sales") or 0)
        lbw_total = round(liq + beer + wine, 2)
        lbw_per_guest = round(lbw_total / g, 4) if g > 0 else 0.0
        glass_per_guest = round(glass / g, 4) if g > 0 else 0.0
        # LSC derived from loyalty per operator's correction.
        lsc_count = round(loy / DOLLARS_PER_LSC) if loy > 0 else 0
        guests_per_lsc = round(g / lsc_count, 4) if lsc_count > 0 else 0.0

        prior = prior_by_legal.get(legal) or {}
        emp = {
            "id": prior.get("id"),
            "canonical_id": prior.get("canonical_id"),
            "name": legal,
            "display_name": prior.get("display_name") or legal,
            "report_name": prior.get("report_name") or legal,
            "job_title": prior.get("job_title") or "Server",
            "quarter": "Q2", "year": 2026,
            "net_sales": net, "guests": g, "guest_count": g, "ppa": ppa,
            "food_sales": food,
            "liquor_sales": liq, "beer_sales": beer, "wine_sales": wine,
            "lbw": lbw_total, "lbw_per_guest": lbw_per_guest,
            "bar_glassware_sales": glass, "glassware_sales": glass,
            "glassware_per_guest": glass_per_guest,
            "loyalty_sales": loy,
            "lsc_count": lsc_count,
            "guests_per_lsc": guests_per_lsc,
            "nps_score":      prior.get("nps_score"),
            "cv_promoters":   prior.get("cv_promoters"),
            "cv_passives":    prior.get("cv_passives"),
            "cv_detractors":  prior.get("cv_detractors"),
            "cv_score":       prior.get("cv_score"),
            "review_mentions": prior.get("review_mentions") or prior.get("rt_mentions"),
            "rt_mentions":     prior.get("rt_mentions") or prior.get("review_mentions"),
            "review_tracker_bonus": prior.get("review_tracker_bonus") or 0,
            "pos_source": "SSD 6.15.26.pdf",
            "pos_parse_job": SSD_JOB_ID,
            "lsc_source_note": f"lsc_count = round(loyalty_sales / ${DOLLARS_PER_LSC:.0f})",
            "loyalty_ocr_corrected": bool(r.get("_loyalty_corrected")),
        }
        new_employees.append(emp)
        new_rows.append({
            "employee_id": emp["id"],
            "frozen_display_name": legal,
            "frozen_report_name": emp["report_name"],
            "frozen_score": None,
            "frozen_metrics": {
                "name": legal,
                "net_sales": net, "guests": g, "guest_count": g, "ppa": ppa,
                "food_sales": food,
                "liquor_sales": liq, "beer_sales": beer, "wine_sales": wine,
                "lbw": lbw_total, "lbw_per_guest": lbw_per_guest,
                "bar_glassware_sales": glass, "glassware_sales": glass,
                "glassware_per_guest": glass_per_guest,
                "loyalty_sales": loy,
                "lsc_count": lsc_count, "guests_per_lsc": guests_per_lsc,
                "nps_score": emp["nps_score"],
                "cv_promoters": emp["cv_promoters"],
                "cv_passives":  emp["cv_passives"],
                "cv_detractors": emp["cv_detractors"],
                "review_mentions": emp["review_mentions"],
                "rt_mentions": emp["rt_mentions"],
            },
        })

    await db.snapshot_workflow_staging.update_one(
        {"_id": staged_doc["_id"]},
        {"$set": {
            "employees": new_employees,
            "rows": new_rows,
            "pos_source": "SSD 6.15.26.pdf",
            "pos_parse_job": SSD_JOB_ID,
            "lsc_derivation": f"lsc_count = round(loyalty_sales / ${DOLLARS_PER_LSC:.0f})",
            "loyalty_ocr_corrections": {
                k: {"corrected": v[0], "parsed": v[1], "reason": v[2]}
                for k, v in LOYALTY_OCR_CORRECTIONS.items()
            },
            "rebuilt_at": "2026-02 (rebuild_q2_from_ssd_pdf v2)",
        }},
    )
    print(f"✓ Staged {len(new_employees)} servers with PDF POS + loyalty-derived LSC.")
    print()

    # Write canonical truth CSV.
    csv_path = "/app/backend/q2_pos_truth_v2.csv"
    with open(csv_path, "w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=[
            "canonical_legal", "pdf_name",
            "net_sales", "guests", "ppa",
            "food_sales", "liquor_sales", "beer_sales", "wine_sales", "lbw_total",
            "bar_glassware_sales", "loyalty_sales", "lsc_count_derived",
            "ocr_corrected",
        ])
        w.writeheader()
        for r in pdf_rows:
            loy = float(r.get("loyalty_sales") or 0)
            w.writerow({
                "canonical_legal":     r["canonical_legal"],
                "pdf_name":            r.get("pdf_name"),
                "net_sales":           r.get("net_sales"),
                "guests":              r.get("guest_count"),
                "ppa":                 r.get("ppa"),
                "food_sales":          r.get("food_sales"),
                "liquor_sales":        r.get("liquor_sales"),
                "beer_sales":          r.get("beer_sales"),
                "wine_sales":          r.get("wine_sales"),
                "lbw_total":           r.get("lbw_total"),
                "bar_glassware_sales": r.get("bar_glassware_sales"),
                "loyalty_sales":       loy,
                "lsc_count_derived":   round(loy / DOLLARS_PER_LSC) if loy > 0 else 0,
                "ocr_corrected":       "YES" if r.get("_loyalty_corrected") else "",
            })
    print(f"✓ Wrote canonical truth -> {csv_path}")
    print()

    # ----------------------------------------------------------------
    # 10. SCORE + FULL LEADERBOARD
    # ----------------------------------------------------------------
    from snapshot_routes import _hydrate_snapshot_employees  # type: ignore
    from scoring_engine import (  # type: ignore
        EmployeeV2, run_full_scoring, generate_hierarchy_rankings,
    )
    staged_doc = await db.snapshot_workflow_staging.find_one({"_id": staged_doc["_id"]})
    hyd = await _hydrate_snapshot_employees(db, staged_doc)

    def _fn(v: Any) -> float:
        try:
            return float(v or 0)
        except (TypeError, ValueError):
            return 0.0

    employees: List[EmployeeV2] = []
    for e in hyd:
        if e.get("no_pos_data_this_period"):
            continue
        employees.append(EmployeeV2(
            id=e.get("id") or e.get("canonical_id") or e.get("employee_id"),
            name=e.get("name") or e.get("display_name"),
            display_name=e.get("display_name") or e.get("name"),
            job_title=e.get("job_title") or "Server",
            quarter="Q2", year=2026,
            net_sales=_fn(e.get("net_sales")),
            guests=int(_fn(e.get("guests") or e.get("guest_count"))),
            ppa=_fn(e.get("ppa")),
            liquor_sales=_fn(e.get("liquor_sales")),
            beer_sales=_fn(e.get("beer_sales")),
            wine_sales=_fn(e.get("wine_sales")),
            glassware_sales=_fn(e.get("glassware_sales") or e.get("bar_glassware_sales")),
            lsc_count=int(_fn(e.get("lsc_count"))),
            nps_score=_fn(e.get("nps_score")),
            cv_promoters=int(_fn(e.get("cv_promoters"))),
            cv_passives=int(_fn(e.get("cv_passives"))),
            cv_detractors=int(_fn(e.get("cv_detractors"))),
            cv_score=0.0,
            review_mentions=int(_fn(e.get("rt_mentions") or e.get("review_mentions"))),
            rt_mentions=int(_fn(e.get("rt_mentions") or e.get("review_mentions"))),
            review_tracker_bonus=_fn(e.get("review_tracker_bonus")),
        ))

    scored = run_full_scoring(employees, settings)
    rk = generate_hierarchy_rankings(scored, settings, first_name_only=False)
    rk_sorted = sorted(rk, key=lambda r: -((r.get("final_score") or r.get("total_score") or 0)))

    print("=" * 138)
    print(f"FULL LEADERBOARD ({len(rk)} servers) — Q2P6W2 STAGED from SSD 6.15.26.pdf with LSC = loyalty/$25")
    print("=" * 138)
    print(f"{'#':>3}  {'name':25}  {'tier':12}  "
          f"{'PPA%':>7}  {'LBW%':>7}  {'Glass%':>7}  {'LSC%':>7}  {'CV%':>6}  "
          f"{'RT bonus':>8}  {'FINAL':>7}   notes")
    print("-" * 138)
    for i, r in enumerate(rk_sorted, start=1):
        legal_match = r.get("display_name") or r.get("name") or "?"
        canonical_legal = reverse.get(_norm(legal_match), legal_match)
        is_phantom = canonical_legal in EXPECTED_PHANTOM_LEGALS
        is_ethan = canonical_legal == "Ethan Dever"
        notes = ""
        if is_phantom:
            notes = " ★ phantom-recovered"
        if is_ethan:
            notes += " 🔧 loyalty OCR-corrected"
        final = _fn(r.get("final_score") or r.get("total_score"))
        tier = r.get("tier_label") or r.get("performance_tier") or "?"
        print(f"{i:>3}  {legal_match:25}  {str(tier):12}  "
              f"{_fn(r.get('ppa_percentage')):>7.2f}  "
              f"{_fn(r.get('lbw_percentage')):>7.2f}  "
              f"{_fn(r.get('glassware_percentage')):>7.2f}  "
              f"{_fn(r.get('lsc_percentage')):>7.2f}  "
              f"{_fn(r.get('cv_percentage') or r.get('cv_score')):>6.2f}  "
              f"{_fn(r.get('review_tracker_bonus')):>8.2f}  "
              f"{final:>7.2f}  {notes}")
    print("-" * 138)
    print()

    scored_names_lc = {_norm(r.get("display_name") or r.get("name")) for r in rk}
    print("9-phantom regression check (after scoring):")
    for legal in EXPECTED_PHANTOM_LEGALS:
        aliases = {_norm(legal)} | {_norm(a) for a in Q2_ALIAS_OVERRIDE.get(legal, [])}
        mark = "✓" if (aliases & scored_names_lc) else "❌"
        print(f"   {mark} {legal}")
    print()

    print("=" * 78)
    print("STAGING ONLY. NO PROMOTION. NO LIVE WRITES.")
    print(f"POS source:  SSD 6.15.26.pdf  (job {SSD_JOB_ID[:8]}...)")
    print(f"LSC source:  loyalty_sales / ${DOLLARS_PER_LSC:.0f}/LSC (per operator's correction)")
    print(f"OCR fixes:   {list(LOYALTY_OCR_CORRECTIONS.keys())}")
    print(f"Truth CSV:   /app/backend/q2_pos_truth_v2.csv")
    print(f"Staged doc:  snapshot_workflow_staging.Q2_REBUILD_STAGED ({len(new_employees)} servers)")
    print("=" * 78)
    print()
    print("HOLD FOR OPERATOR REVIEW. Do not promote.")


if __name__ == "__main__":
    asyncio.run(main())
